ptf ~


# MAP AREA AND VENT COORDINATES
#MIN_EASTING = -50000
#MAX_EASTING = 50000
#MIN_NORTHING = -50000
#MAX_NORTHING = 50000
#VENT_EASTING = 0
#VENT_NORTHING = 0

VENT_EASTING = 242782
VENT_NORTHING = 8196548
MIN_EASTING = VENT_EASTING - 60000
MAX_EASTING = VENT_EASTING + 60000
MIN_NORTHING = VENT_NORTHING - 60000
MAX_NORTHING = VENT_NORTHING + 60000

RUN_MODE = "custom points"

OUTPUT_FILE_NAME = "pulu_sim.dat"

# GROUND GRID RESOLUTION (DEFAULT MAP HAS 1000 GRID CELLS)
GROUND_GRID_SIZE = 100**2

# UMBRELLA CLOUD GEOMETRY PARAMETERS
# Ellipse full axis length, NOT semi-axis
ELLIPSE_MAJOR_AXIS =  ~  ellipse_major_axis  ~ 
ELLIPSE_MINOR_AXIS =  ~  ellipse_minor_axis  ~ 
ELLIPSE_GRID_STEP = 250

# ERUPTION PARAMETERS
TOTAL_ERUPTED_MASS =  ~  total_erupted_mass  ~ 
COLUMN_HEIGHT =  ~  column_height  ~ 
BULK_DENSITY = 1500
PARTICLE_DENSITY_MAX = 1500
PARTICLE_DENSITY_MIN = 1500
DIFFUSION_COEF =  ~  diffusion_coef  ~ 
WIND_SPEED =  ~  wind_speed  ~ 
WIND_DIRECTION =  ~  wind_direction  ~ 
ETA = 1             # unitless

# DEFINE PHI INTERVALS (min | max phi according to TGSD)
MAX_PHI = -5
MIN_PHI = 5
# TGSD_SIGMA =  1.687
# TGSD_MEAN =  -2.398
TGSD_SIGMA =  ~  tgsd_sigma  ~ 
TGSD_MEAN =  ~  tgsd_mean  ~ 
# TGSD_SIGMA =  0.1 
# TGSD_MEAN =  0.5  

# SIMULATED PHI INTERVALS (phi interval to be simulated)
SIMULATED_MAX_PHI = -5
SIMULATED_MIN_PHI = 5
STEP_PHI = 1

# CONSTANTS FOR SETTLING VELOCITY CALCULATION
ATMOSPHERE_LEVEL_STEP = 500  # 500 m thick atmosphere slices
RHO_A_S = 1.225  # density at sea level
G = 9.81  # gravitational constant
AIR_VISC = 1.8325e-5  # air viscosity in N s / m^2 at 24C

DISPERSAL_AXIS_POINTS_NUMBER = 500  # total number of points
DISPERSAL_AXIS_POINTS_DISTANCE = 100  # distance between two points
